/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.sw.tablas.formas;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import uam.pvoe.sw.tablas.operaciones.OperacionesTabla;

/**
 *
 * @author ALUMNO11
 */
public class FrmTablas extends javax.swing.JFrame {

    /**
     * Creates new form FrmTablas
     */
    public FrmTablas() {
        initComponents();
        configurarTablaBasica();
        generarTabla();
    }
    
    private void configurarTablaBasica(){
        DefaultTableModel modelo = new DefaultTableModel(0,0);
        tblTablaSimple.setModel(modelo);
}
    
    private void generarTabla(){
        Vector columnas = new Vector();
        columnas.add("Columna A");
        columnas.add("Columna B");
        columnas.add("Columna C");
        columnas.add("Columna D");
        columnas.add("Columna E");
        
        
        Vector todasLasFilas = new Vector();
        Vector fila = new Vector();
        
        
        fila.add("1_1");
        fila.add("1_2");
        fila.add("1_3");
        fila.add("1_4");
        fila.add("1_5");
        
        todasLasFilas.add(fila);
        
        fila = new Vector();
        
        fila.add("2_1");
        fila.add("2_2");
        fila.add("2_3");
        fila.add("2_4");
        fila.add("2_5");
   
        todasLasFilas.add(fila);
        
        DefaultTableModel modelo = new DefaultTableModel(0,0);
        modelo.setDataVector(todasLasFilas, columnas);
        
        tblTablaSimple.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlTablaSimple = new javax.swing.JScrollPane();
        tblTablaSimple = new javax.swing.JTable();
        scrlTablaDinamica = new javax.swing.JScrollPane();
        tblTablaDinamica = new javax.swing.JTable();
        lblFilas = new javax.swing.JLabel();
        txtFilas = new javax.swing.JTextField();
        lblColumnas = new javax.swing.JLabel();
        txtColumnas = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        btnAgregarFila = new javax.swing.JButton();
        btnAgregarColumna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTablaSimple.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrlTablaSimple.setViewportView(tblTablaSimple);

        tblTablaDinamica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrlTablaDinamica.setViewportView(tblTablaDinamica);

        lblFilas.setText("Filas");

        lblColumnas.setText("Columnas");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnAgregarFila.setText("Agregar Fila");
        btnAgregarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFilaActionPerformed(evt);
            }
        });

        btnAgregarColumna.setText("Agregar Columna");
        btnAgregarColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarColumnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrlTablaDinamica, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                            .addComponent(scrlTablaSimple)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGenerar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblFilas)
                                .addComponent(lblColumnas)
                                .addComponent(txtFilas, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(txtColumnas)))
                        .addGap(33, 33, 33)
                        .addComponent(btnAgregarFila)
                        .addGap(37, 37, 37)
                        .addComponent(btnAgregarColumna)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(scrlTablaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(scrlTablaDinamica, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblFilas)
                .addGap(18, 18, 18)
                .addComponent(txtFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblColumnas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnAgregarFila)
                    .addComponent(btnAgregarColumna))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
       int nFilas = Integer.parseInt(txtFilas.getText());
       int nCols = Integer.parseInt(txtColumnas.getText());
       
       generarTablaDinamica(nFilas,nCols);
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnAgregarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFilaActionPerformed
      DefaultTableModel modelo = (DefaultTableModel)tblTablaDinamica.getModel();
      
      Vector nuevaFila = new Vector();
      modelo.addRow(nuevaFila);
      tblTablaDinamica.setModel(modelo);
    }//GEN-LAST:event_btnAgregarFilaActionPerformed

    private void btnAgregarColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarColumnaActionPerformed
      DefaultTableModel modelo = (DefaultTableModel)tblTablaDinamica.getModel();
      
      modelo.addColumn("NUEVA");
      tblTablaDinamica.setModel(modelo); 
    }//GEN-LAST:event_btnAgregarColumnaActionPerformed
    
    private void  generarTablaDinamica(int nF, int nC){
        OperacionesTabla operaciones = new OperacionesTabla();
        Vector cols = operaciones.generaColumnas(nC);
        Vector filas= operaciones.generaFilas(nF, nC);
        
        DefaultTableModel modelo = new DefaultTableModel(0,0);
        modelo.setDataVector(filas, cols);
        tblTablaDinamica.setModel(modelo);

    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarColumna;
    private javax.swing.JButton btnAgregarFila;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel lblColumnas;
    private javax.swing.JLabel lblFilas;
    private javax.swing.JScrollPane scrlTablaDinamica;
    private javax.swing.JScrollPane scrlTablaSimple;
    private javax.swing.JTable tblTablaDinamica;
    private javax.swing.JTable tblTablaSimple;
    private javax.swing.JTextField txtColumnas;
    private javax.swing.JTextField txtFilas;
    // End of variables declaration//GEN-END:variables
}
