/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.CheckBoxes;

import java.util.LinkedList;
import javax.swing.JCheckBox;

/**
 *
 * @author ALUMNA16
 */
public class FrmCheckBoxes extends javax.swing.JFrame {
    LinkedList<JCheckBox>opciones;
    /**
     * Creates new form FrmCheckBoxes
     */
    public FrmCheckBoxes() {
        initComponents();
        opciones = new LinkedList<>();
        agruparCheckBoxes();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbOpcionA = new javax.swing.JCheckBox();
        lblTitulo = new javax.swing.JLabel();
        lblInstrucciones = new javax.swing.JLabel();
        cbOpcionB = new javax.swing.JCheckBox();
        cbOpcionC = new javax.swing.JCheckBox();
        cbOpcionD = new javax.swing.JCheckBox();
        lblSeleccionUnica = new javax.swing.JLabel();
        cbOpcionUnica = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbOpcionA.setText("Opcion A");

        lblTitulo.setText("Uso de Check Boxes");

        lblInstrucciones.setText("Seleccione las opciones");

        cbOpcionB.setText("Opcion B");

        cbOpcionC.setText("Opcion C");

        cbOpcionD.setText("Opcion D");

        lblSeleccionUnica.setText("Elige (Marca Sí)");

        cbOpcionUnica.setText("Opcion Única");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbOpcionA)
                        .addGap(33, 33, 33)
                        .addComponent(cbOpcionB)
                        .addGap(42, 42, 42)
                        .addComponent(cbOpcionC))
                    .addComponent(lblInstrucciones)
                    .addComponent(cbOpcionD)
                    .addComponent(lblSeleccionUnica)
                    .addComponent(cbOpcionUnica))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(19, 19, 19)
                .addComponent(lblInstrucciones)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOpcionA)
                    .addComponent(cbOpcionB)
                    .addComponent(cbOpcionC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbOpcionD)
                .addGap(57, 57, 57)
                .addComponent(lblSeleccionUnica)
                .addGap(27, 27, 27)
                .addComponent(cbOpcionUnica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        leerCheckBoxes();
        leerOpcionUnica();
    }//GEN-LAST:event_btnRegistrarActionPerformed
    private void agruparCheckBoxes(){
        
        opciones.add(cbOpcionA);
        opciones.add(cbOpcionB);
        opciones.add(cbOpcionC);
        opciones.add(cbOpcionD);
        
    }
    
    private void leerCheckBoxes(){
    
        for(int i =0; i<opciones.size(); i++){
            JCheckBox aux = opciones.get(i);
            if(aux.isSelected()){
                System.out.println(aux.getText());
            }
        }
    }
    
    private void leerOpcionUnica(){
        if(cbOpcionUnica.isSelected())
        {
            System.out.println("Elegiste Si");
        } else{
            System.out.println("Elegiste NO");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCheckBoxes().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox cbOpcionA;
    private javax.swing.JCheckBox cbOpcionB;
    private javax.swing.JCheckBox cbOpcionC;
    private javax.swing.JCheckBox cbOpcionD;
    private javax.swing.JCheckBox cbOpcionUnica;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblSeleccionUnica;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
