/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.pvoe.formas;

import java.io.File;
import java.text.ParseException;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import uam.azc.pvoe.modelos.Administrador;
import uam.azc.pvoe.modelos.Cliente;
import uam.azc.pvoe.modelos.Proveedor;
import uam.azc.pvoe.operaciones.LeerUsuarioLog;
import uam.azc.pvoe.operaciones.ListaProveedores;


/**
 *
 * @author Julio Cesar Haro Capetillo 2202000415
 */
public class BienvenidaFrm extends javax.swing.JFrame {
    
    private Cliente cli = new Cliente();
    private Administrador ad = new Administrador();
    public LeerUsuarioLog log = new LeerUsuarioLog();

    
    /**
     * Creates new form BienvenidaFrm
     */
    public BienvenidaFrm() throws ParseException {
        initComponents();
        lblNombreUsuario.setVisible(false);
        log.leerAdministrador("administradorLog.txt");
        log.leerCliente("clienteLog.txt");
        recuperaUsuario();
        lblNombreUsuario.setVisible(true);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrarProveedor = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblListaClientes = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblProveedores = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        btnConsultarCatalogo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrarPublicacion = new javax.swing.JButton();
        lblNombreDos = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDeudor = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Bienvenido");

        lblNombreUsuario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblNombreUsuario.setText("_nombre de Usuario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Consultar Catálogo");

        btnRegistrarProveedor.setText("Registrar una editorial");
        btnRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lblListaClientes.setText("*Lista de Clientes (Sólo administradores)");

        btnClientes.setText("Consultar Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        lblProveedores.setText("*Lista de Proveedores");

        btnProveedores.setText("Consultar Editoriales");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        jLabel5.setText("* Registrar proveedor (Sólo administradores)");

        btnConsultarCatalogo.setText("Consultar Catálogo");
        btnConsultarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCatalogoActionPerformed(evt);
            }
        });

        jLabel6.setText("*Registrar una Publicación");

        btnRegistrarPublicacion.setText("Registrar Publicación");
        btnRegistrarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPublicacionActionPerformed(evt);
            }
        });

        lblNombreDos.setText("Nombre");

        lblDireccion.setText("Direccion");

        lblEmail.setText("E-mail");

        lblDeudor.setText("Deudor");

        lblTelefono.setText("Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrarProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultarCatalogo)
                                .addGap(167, 167, 167)
                                .addComponent(lblDeudor))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProveedores)
                                .addGap(149, 149, 149)
                                .addComponent(btnRegistrarPublicacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblListaClientes)
                                .addGap(182, 182, 182)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnClientes))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProveedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblNombreDos)
                            .addComponent(lblDireccion)
                            .addComponent(lblTelefono))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblNombreUsuario)
                    .addComponent(lblNombreDos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEmail))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarCatalogo)
                            .addComponent(lblDeudor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProveedores)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProveedores)
                            .addComponent(btnRegistrarPublicacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblListaClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion)
                    .addComponent(btnRegistrarProveedor))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorActionPerformed
         if(ad.isAdmin()==true && cli.getNombre()==null){
            JOptionPane.showMessageDialog(this, "Bienvenido administrador");
            
            RegistrarProveedor proveedor = new RegistrarProveedor();
            proveedor.setVisible(true);
            this.dispose();
            
        }else /*log.leerAdministrador("administraodrLog.txt").isAdmin()==true)*/{
            
            JOptionPane.showMessageDialog(this, "Restringido. \n Esta opcion es para Administradores solamente");
        }
    }//GEN-LAST:event_btnRegistrarProveedorActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
        File borrarAdmin = new File("administradorLog.txt");
        File borrarCliente = new File("clienteLog.txt");
        borrarAdmin.delete();
        borrarCliente.delete();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        
        if(ad.isAdmin()==true && cli.getNombre()==null){
            JOptionPane.showMessageDialog(this, "Bienvenido administrador");
            FrmClienesTabla tablaClientes;
            try {
                tablaClientes = new FrmClienesTabla();
                
            tablaClientes.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(BienvenidaFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
            
        }else /*log.leerAdministrador("administraodrLog.txt").isAdmin()==true)*/{
            
            JOptionPane.showMessageDialog(this, "Restringido. \n Esta opcion es para Administradores solamente");
        }
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnConsultarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCatalogoActionPerformed
        // TODO add your handling code here:

            Publicaciones publicaciones = new Publicaciones();
            publicaciones.setVisible(true);
            this.dispose();
            
    }//GEN-LAST:event_btnConsultarCatalogoActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        Editoriales publicaciones;
        try {
            publicaciones = new Editoriales();
             publicaciones.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(BienvenidaFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        this.dispose();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnRegistrarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPublicacionActionPerformed
        // TODO add your handling code here:
            
        if(ad.isAdmin()==true && cli.getNombre()==null){
            JOptionPane.showMessageDialog(this, "Bienvenido administrador");
           
            RegistrarProveedor publicaciones = new RegistrarProveedor();
            publicaciones.setVisible(true);
            this.dispose();
            
        }else /*log.leerAdministrador("administraodrLog.txt").isAdmin()==true)*/{
            
            JOptionPane.showMessageDialog(this, "Restringido. \n Esta opcion es para Administradores solamente");
        }
        
    }//GEN-LAST:event_btnRegistrarPublicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BienvenidaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BienvenidaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BienvenidaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BienvenidaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BienvenidaFrm().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(BienvenidaFrm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }
    /**
     * Método que recupera al usuario y genera su archivo
     */
    public void recuperaUsuario() throws ParseException{
        ad = log.leerAdministrador("administradorLog.txt");
        cli= log.leerCliente("clienteLog.txt");
        System.out.println("pruebaBienvenida"+ ad+ "\n"+cli);
        if(ad.getNombre()==null){
            
            lblNombreUsuario.setText(cli.getNombre());
            lblNombreDos.setText(cli.getNombre());
            lblEmail.setText(cli.getEmail());
            lblDireccion.setText(cli.getDireccion());
            lblTelefono.setText(cli.getTelefono());
            if(cli.isDeudor()){
                lblDeudor.setText("Usted debe");
            }else{
                lblDeudor.setText("Felicidades usted no debe");
            }
        } else{
            
            lblNombreUsuario.setText(ad.getNombre());
        }
    }
    /**
     * Método que recupera al usuario
     */
    public void dameElUsuario() throws ParseException{
        recuperaUsuario();
    
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConsultarCatalogo;
    private javax.swing.JToggleButton btnProveedores;
    private javax.swing.JButton btnRegistrarProveedor;
    private javax.swing.JButton btnRegistrarPublicacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDeudor;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblListaClientes;
    private javax.swing.JLabel lblNombreDos;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblProveedores;
    private javax.swing.JLabel lblTelefono;
    // End of variables declaration//GEN-END:variables
}
