/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.pvoe.formas;

import java.io.File;
import java.text.ParseException;
import java.util.Enumeration;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import uam.azc.pvoe.operaciones.TablaClientes;

/**
 *
 * @author Julio Cesar Haro Capetillo 2202000415
 */
public class FrmClienesTabla extends javax.swing.JFrame {

    /**
     * Creates new form FrmClienesTabla
     */
    public FrmClienesTabla() throws ParseException {
        initComponents();
        llenarTablaInicial();
        juntaRbClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelTodosClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        rbTodos = new javax.swing.JRadioButton();
        rbDeudores = new javax.swing.JRadioButton();
        btnConsultar = new javax.swing.JButton();
        lblTodosLosClientes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane1.setViewportView(tblClientes);

        rbTodos.setText("Todos los Clientes");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        rbDeudores.setText("Clientes Deudores");

        btnConsultar.setText("Consultar clientes");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTodosClientesLayout = new javax.swing.GroupLayout(panelTodosClientes);
        panelTodosClientes.setLayout(panelTodosClientesLayout);
        panelTodosClientesLayout.setHorizontalGroup(
            panelTodosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTodosClientesLayout.createSequentialGroup()
                .addGroup(panelTodosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTodos)
                    .addGroup(panelTodosClientesLayout.createSequentialGroup()
                        .addComponent(rbDeudores)
                        .addGap(38, 38, 38)
                        .addComponent(btnConsultar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelTodosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTodosClientesLayout.setVerticalGroup(
            panelTodosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTodosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTodosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDeudores)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTodosLosClientes.setText("Todos Los clientes");

        jButton1.setText("Volver a Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar Sesión");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTodosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTodosLosClientes))
                        .addContainerGap(7, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTodosLosClientes)
                .addGap(29, 29, 29)
                .addComponent(panelTodosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        BienvenidaFrm bienvenida;
        try {
            bienvenida = new BienvenidaFrm();
            bienvenida.setVisible(true);
            this.dispose();
            
        } catch (ParseException ex) {
            Logger.getLogger(FrmClienesTabla.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
        File borrarAdmin = new File("administradorLog.txt");
        File borrarCliente = new File("clienteLog.txt");
        borrarAdmin.delete();
        borrarCliente.delete();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String cliente = leerProcedenciaSeleccionado();
        if(cliente.compareTo("Todos los Clientes")==0){
            try {
                llenarTablaInicial();
            } catch (ParseException ex) {
                Logger.getLogger(FrmClienesTabla.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else if(cliente.compareTo("Clientes Deudores")==0){
            
            try {
                llenarTablaDeudores();
            } catch (ParseException ex) {
                Logger.getLogger(FrmClienesTabla.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClienesTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClienesTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClienesTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClienesTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmClienesTabla().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrmClienesTabla.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    /**
     * Llena la tabla con todos los datos sin discriminar por tipo de unidad.
     */
        private void llenarTablaInicial() throws ParseException{
        DefaultTableModel modelo = new DefaultTableModel(0,0);
        TablaClientes llenar = new TablaClientes();
        Vector listaTitulos = llenar.tituloColumnas();
        Vector filas = llenar.elementosCelda();
        
        modelo.setDataVector(filas, listaTitulos); 
        tblClientes.setModel(modelo);
    }
        /**
         * Metodo que llena la tabla de los Deudores
         * @throws ParseException se arroja cuando no funciona el metodo elemtosCeldaDeudores
         */
        private void llenarTablaDeudores() throws ParseException{
        DefaultTableModel modelo = new DefaultTableModel(0,0);
        TablaClientes llenar = new TablaClientes();
        Vector listaTitulos = llenar.tituloColumnas();
        Vector filas = llenar.elementosCeldaDeudores();
        
        modelo.setDataVector(filas, listaTitulos); 
        tblClientes.setModel(modelo);
        }
        /**
         * Lee las opciones consultadas del grupo de botones de los clientes
         * @return un String con el valor
         */
        private String leerProcedenciaSeleccionado(){
        Enumeration<AbstractButton> botonElegido= buttonGroup1.getElements();
        String seleccionado = "";
        while(botonElegido.hasMoreElements()){
            
            JRadioButton rbAux =(JRadioButton)botonElegido.nextElement();
            if(rbAux.isSelected()){
                //System.out.println(rbAux.getText());
                seleccionado = rbAux.getText();
                break;
            }
        
        }
        return seleccionado;
        
    
    }   
    /**
     * Metodo que junta los radio butons de clientes y clientes deudores
     */ 
    private void juntaRbClientes(){
    
        buttonGroup1.add(rbTodos);
        buttonGroup1.add(rbDeudores);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTodosLosClientes;
    private javax.swing.JPanel panelTodosClientes;
    private javax.swing.JRadioButton rbDeudores;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
