/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.pvoe.formas;

import java.io.File;
import java.text.ParseException;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import uam.azc.pvoe.modelos.Proveedor;
import uam.azc.pvoe.operaciones.ListaProveedores;
import uam.azc.pvoe.operaciones.TablaClientes;
import uam.azc.pvoe.operaciones.TablaPublicaciones;

/**
 * Ventana en donde se muestran los libros, ya sea por tipo, o por editorial
 * @author Julio Cesar Haro Capetillo 2202000415
 */
public class Publicaciones extends javax.swing.JFrame {
    private ListaProveedores prove = new ListaProveedores();
    LinkedList<Proveedor> proveedores = prove.llenaProveedor();
    
    private String eleccionRb;
    /**
     * Creates new form Publicaciones
     */
    public Publicaciones() {
        initComponents();
        buttonGroupDiv();
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContenido1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContenido = new javax.swing.JTable();
        rbLibros = new javax.swing.JRadioButton();
        rbRevistas = new javax.swing.JRadioButton();
        btnConsultar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        tblContenido1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblContenido1.setPreferredSize(new java.awt.Dimension(700, 600));
        jScrollPane2.setViewportView(tblContenido1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Artículos de lectura disponibles.");

        tblContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblContenido.setPreferredSize(new java.awt.Dimension(700, 600));
        jScrollPane1.setViewportView(tblContenido);

        rbLibros.setText("Catalogo de libros");

        rbRevistas.setText("Catalogo de Revistas");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInicio.setText("Volver al inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbRevistas)
                            .addComponent(lblTitulo))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbLibros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLibros)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbRevistas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio)
                    .addComponent(btnCerrarSesion))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        eleccionRb = leerProcedenciaSeleccionado();
        System.out.println(eleccionRb);
        if(eleccionRb!=null && eleccionRb!=""){
            System.out.println("Ha elegido la opcion"+ eleccionRb);
        }else{
            System.out.println("los botones estan vacios");
        }

        if(eleccionRb.compareTo("Catalogo de libros")==0){
            try {
                llenarTablaInicial();
            } catch (ParseException ex) {
                Logger.getLogger(Publicaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else if(eleccionRb.compareTo("Catalogo de Revistas")==0){
            try {
                llenarTablaRevistas();
            } catch (ParseException ex) {
                Logger.getLogger(Publicaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
   
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
       BienvenidaFrm bienvenida;
       
        try {
            bienvenida = new BienvenidaFrm();
            bienvenida.setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(Publicaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
        File borrarAdmin = new File("administradorLog.txt");
        File borrarCliente = new File("clienteLog.txt");
        borrarAdmin.delete();
        borrarCliente.delete();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Publicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Publicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Publicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Publicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Publicaciones().setVisible(true);
            }
        });
    }
        private String leerProcedenciaSeleccionado(){
        Enumeration<AbstractButton> botonElegido= buttonGroup1.getElements();
        String seleccionado = "";
        while(botonElegido.hasMoreElements()){
            
            JRadioButton rbAux =(JRadioButton)botonElegido.nextElement();
            if(rbAux.isSelected()){
                //System.out.println(rbAux.getText());
                seleccionado = rbAux.getText();
                break;
            }
        
        }
        return seleccionado;
        
    }
    

    /**
     * método que junta las opciones revistas y libros en un sólo grupo de radiobuttons
     */
    private void buttonGroupDiv(){
        buttonGroup1.add(rbRevistas);
        buttonGroup1.add(rbLibros);
    }
    /**
     * Llena toda la lista con las editoriales para el combo box
     * @param editorial recibe la editorial
     */

        /**
         * Método que llena la tabla con Los libros
         * @throws ParseException 
         */
        private void llenarTablaInicial() throws ParseException{
        DefaultTableModel modelo = new DefaultTableModel(0,0);
        TablaPublicaciones llenar = new TablaPublicaciones();
        Vector listaTitulos = llenar.tituloColumnasLibro();
        Vector filas = llenar.elementosCeldaLibro();
        
        modelo.setDataVector(filas, listaTitulos); 
        tblContenido.setModel(modelo);
    }
        /**
         * Método que llena la tabla con Las revistas
         * @throws ParseException 
         */
        private void llenarTablaRevistas() throws ParseException{
        DefaultTableModel modelo = new DefaultTableModel(0,0);
        TablaPublicaciones llenar = new TablaPublicaciones();
        Vector listaTitulos = llenar.tituloColumnasRevista();
        Vector filas = llenar.elementosCeldaRevista();
        
        modelo.setDataVector(filas, listaTitulos); 
        tblContenido.setModel(modelo);
    }
     
 /**
         * Método que llena la tabla con Las revistas
         * @throws ParseException 
         */
        private void llenarTablaRevistasPorrua() throws ParseException{
        DefaultTableModel modelo = new DefaultTableModel(0,0);
        TablaPublicaciones llenar = new TablaPublicaciones();
        Vector listaTitulos = llenar.tituloColumnasRevista();
        Vector filas = llenar.elementosCeldaRevistaPorrua();
        
        modelo.setDataVector(filas, listaTitulos); 
        tblContenido.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnInicio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbLibros;
    private javax.swing.JRadioButton rbRevistas;
    private javax.swing.JTable tblContenido;
    private javax.swing.JTable tblContenido1;
    // End of variables declaration//GEN-END:variables
}
