/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.pvoe.formas;

import java.io.File;
import java.text.ParseException;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;
import uam.azc.pvoe.modelos.Libro;
import uam.azc.pvoe.modelos.Revista;
import uam.azc.pvoe.operaciones.LeerUsuarioLog;
import uam.azc.pvoe.operaciones.ListaLibro;
import uam.azc.pvoe.operaciones.ListaReviistas;
import uam.azc.pvoe.operaciones.UsuarioLogeado;

/**
 *
 * @author Julio Cesar Haro Capetillo 2202000415
 */
public class RegistrarPublicacion extends javax.swing.JFrame {
    Libro libro = new Libro();
    Revista revista = new Revista();
    private String tipo;
    private UsuarioLogeado log = new UsuarioLogeado();
    private ListaLibro lib = new ListaLibro();
    private LinkedList<Libro> libros = lib.llenaLib();
    private ListaReviistas rev = new ListaReviistas();
    private LinkedList<Revista> revistas = rev.llenaRev();
    
    /**
     * Creates new form RegistrarPublicacion
     */
    public RegistrarPublicacion() {
        initComponents();
        lblNumeroRevista.setVisible(false);
        lblAdquisiciones.setVisible(false);
        juntaRbPublicaciones();
        txtNoRevista.setVisible(false);
        txtNumeroDisponible.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbLibro = new javax.swing.JRadioButton();
        rbRevista = new javax.swing.JRadioButton();
        txtISBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        lblNumeroRevista = new javax.swing.JLabel();
        txtNoRevista = new javax.swing.JTextField();
        lblAdquisiciones = new javax.swing.JLabel();
        txtNumeroDisponible = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnTipo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Registrar nueva Adquisición");

        jLabel1.setText("*Ingrese el título");

        jLabel2.setText("*Ingrese el ISBN");

        rbLibro.setText("Libro");

        rbRevista.setText("Revista");

        jLabel3.setText("*Ingrese la Editorial");

        lblNumeroRevista.setText("Numero de revista");

        lblAdquisiciones.setText("Numero de adquisisciones");

        jLabel4.setText("Seleccionar tipo");

        btnTipo.setText("Seleccionar");
        btnTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnInicio.setText("Volver al Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(lblTitulo)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbLibro)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbRevista)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(btnTipo))
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroRevista)
                            .addComponent(txtNoRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdquisiciones))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar)
                            .addComponent(txtNumeroDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addComponent(btnInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLibro)
                    .addComponent(rbRevista)
                    .addComponent(jLabel4)
                    .addComponent(btnTipo))
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroRevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAdquisiciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnInicio)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoActionPerformed
        // TODO add your handling code here:
        tipo = leerProcedenciaSeleccionado();
        if(tipo=="Libro"){
            libro.setTipo(tipo);
        
        }else{
            revista.setTipo(tipo);
            txtNoRevista.setVisible(true);
            txtNumeroDisponible.setVisible(true);
            lblNumeroRevista.setVisible(true);
            lblAdquisiciones.setVisible(true);
        }
        
        
    }//GEN-LAST:event_btnTipoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        recuperaDatos();
        Publicaciones publicaciones = new Publicaciones();
        publicaciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        BienvenidaFrm bienvenida;
        try {
            bienvenida = new BienvenidaFrm();
            bienvenida.setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarPublicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnInicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
        File borrarAdmin = new File("administradorLog.txt");
        File borrarCliente = new File("clienteLog.txt");
        borrarAdmin.delete();
        borrarCliente.delete();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPublicacion().setVisible(true);
            }
        });
    }
    /**
     * Método que junta las opciones de radio button
     */
    
    private void juntaRbPublicaciones(){
        buttonGroup1.add(rbLibro);
        buttonGroup1.add(rbRevista);
    
    }
    
    /**
     * Lee el botón seleccionado
     * @return el valor de la procedencia seleccionada
     */
        private String leerProcedenciaSeleccionado(){
        Enumeration<AbstractButton> botonElegido= buttonGroup1.getElements();
        String seleccionado = "";
        while(botonElegido.hasMoreElements()){
            
            JRadioButton rbAux =(JRadioButton)botonElegido.nextElement();
            if(rbAux.isSelected()){
                //System.out.println(rbAux.getText());
                seleccionado = rbAux.getText();
                break;
            }
        
        }
        return seleccionado;
        
    }
    
    public void recuperaDatos(){
        tipo = leerProcedenciaSeleccionado();
        if(tipo=="Libro"){
            libro.setTitulo(txtTitulo.getText());
            libro.setIsbn(txtISBN.getText());
            libro.setEditorial(txtEditorial.getText());
            libros.add(libro);
            log.archivoLibros("libros.txt", libros);
        }else{
            lblNumeroRevista.setVisible(true);
            lblAdquisiciones.setVisible(true);
            txtNoRevista.setVisible(true);
            txtNumeroDisponible.setVisible(true);
            revista.setTitulo(txtTitulo.getText());
            revista.setIsbn(txtISBN.getText());
            revista.setEditorial(txtEditorial.getText());
            revista.setNum(Integer.parseInt(txtNoRevista.getText()));
            revista.setCantidadDisponible(Integer.parseInt(txtNumeroDisponible.getText()));
            revistas.add(revista);
            log.archivoRevistas("revistas.txt", revistas);
        }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnTipo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAdquisiciones;
    private javax.swing.JLabel lblNumeroRevista;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbLibro;
    private javax.swing.JRadioButton rbRevista;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNoRevista;
    private javax.swing.JTextField txtNumeroDisponible;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
