/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.sw.textos.formas;

import java.awt.Color;

/**
 *
 * @author ALUMNA16
 */
public class FrmTextos extends javax.swing.JFrame {

    /**
     * Creates new form FrmTextos
     */
    public FrmTextos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTittle = new javax.swing.JLabel();
        txtTextoA = new javax.swing.JTextField();
        txtTextoB = new javax.swing.JTextField();
        txtTextoC = new javax.swing.JTextField();
        lblTextoA = new javax.swing.JLabel();
        lblTextoB = new javax.swing.JLabel();
        lblTextoC = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblLimpiar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Texto  y eventos");

        lblTittle.setText("Texto y Eventos");

        txtTextoA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTextoAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTextoAFocusLost(evt);
            }
        });
        txtTextoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTextoAKeyReleased(evt);
            }
        });

        txtTextoB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTextoBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTextoBFocusLost(evt);
            }
        });
        txtTextoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTextoBActionPerformed(evt);
            }
        });
        txtTextoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTextoBKeyReleased(evt);
            }
        });

        txtTextoC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTextoCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTextoCFocusLost(evt);
            }
        });
        txtTextoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTextoCActionPerformed(evt);
            }
        });

        lblTextoA.setText("Texto A");

        lblTextoB.setText("Texto B");

        lblTextoC.setText("Texto C");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblLimpiar.setText("Limpiar Campos");
        lblLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTextoC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtTextoB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTextoA, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTextoA))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTextoB))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTextoC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTittle)
                .addGap(18, 18, 18)
                .addComponent(lblTextoA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTextoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lblTextoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTextoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblTextoC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTextoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(lblLimpiar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTextoAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoAKeyReleased
        // TODO add your handling code here:
        System.out.println("Estas escribiendo!!!");
        String leido = txtTextoA.getText();
        System.out.println(leido);
        txtTextoB.setText(leido.toUpperCase());
    }//GEN-LAST:event_txtTextoAKeyReleased

    private void txtTextoBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoBKeyReleased
        // TODO add your handling code here:
        
        
        //txtTextoB.setText(txtTextoA.getText().toUpperCase());
    }//GEN-LAST:event_txtTextoBKeyReleased

    private void txtTextoAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTextoAFocusGained
        // TODO add your handling code here:
        txtTextoA.setBackground(Color.LIGHT_GRAY);
        
        
    }//GEN-LAST:event_txtTextoAFocusGained

    private void txtTextoAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTextoAFocusLost
        // TODO add your handling code here:
        txtTextoA.setBackground(Color.WHITE);
        
        
    }//GEN-LAST:event_txtTextoAFocusLost

    private void txtTextoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTextoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTextoBActionPerformed

    private void txtTextoBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTextoBFocusLost
        // TODO add your handling code here:
        txtTextoB.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_txtTextoBFocusLost

    private void txtTextoCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTextoCFocusLost
        txtTextoC.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtTextoCFocusLost

    private void txtTextoBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTextoBFocusGained
        // TODO add your handling code here:
        txtTextoB.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtTextoBFocusGained

    private void txtTextoCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTextoCFocusGained
        // TODO add your handling code here:
        txtTextoC.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtTextoCFocusGained

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        System.out.println("Estas registrando:");
        String leido = txtTextoA.getText();
        System.out.println(leido);
        
        txtTextoB.setText(leido.toUpperCase());
        System.out.println(txtTextoB.getText());
        String leido3 = txtTextoC.getText();
        System.out.println(leido3);
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtTextoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTextoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTextoCActionPerformed

    private void lblLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseClicked
        // TODO add your handling code here:
        txtTextoA.setText("");
        txtTextoB.setText("");
        txtTextoC.setText("");
    }//GEN-LAST:event_lblLimpiarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTextos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTextos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTextos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTextos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTextos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JLabel lblTextoA;
    private javax.swing.JLabel lblTextoB;
    private javax.swing.JLabel lblTextoC;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JTextField txtTextoA;
    private javax.swing.JTextField txtTextoB;
    private javax.swing.JTextField txtTextoC;
    // End of variables declaration//GEN-END:variables
}
